### ISSUE TITLE
MacOS race condition in setuptab.test.js

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#155]
This occurs occasionally in GHA, I'm not sure if it also reproduces locally on MacOS. The tests pass, but jest issues this warning, which we turned into an error for our own benefit.

```
ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.

      at runWithJestRealTimers (node_modules/@testing-library/dom/dist/helpers.js:38:8)
      at jestFakeTimersAreEnabled (node_modules/@testing-library/dom/dist/helpers.js:57:12)
      at MutationObserverImpl.checkRealTimersCallback [as _callback] (node_modules/@testing-library/dom/dist/wait-for.js:114:49)
      at notifyMutationObservers (node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:158:14)
      at node_modules/jsdom/lib/jsdom/living/helpers/mutation-observers.js:133:5
  console.error
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
        at SetupTab (/Users/runner/work/invest-workbench/invest-workbench/src/renderer/components/SetupTab/index.jsx:67:22)
        at div
        at Transition (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-transition-group/cjs/Transition.js:133:30)
        at Fade (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/Fade.js:36:24)
        at TabPane (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/TabPane.js:46:24)
        at div
        at /Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/TabContent.js:19:23
        at div
        at Col (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/Col.js:22:23)
        at div
        at Row (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/Row.js:24:23)
        at TabContainer (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/TabContainer.js:19:62)
        at InvestTab (/Users/runner/work/invest-workbench/invest-workbench/src/renderer/components/InvestTab/index.jsx:50:22)
        at div
        at Transition (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-transition-group/cjs/Transition.js:133:30)
        at Fade (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/Fade.js:36:24)
        at TabPane (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-bootstrap/cjs/TabPane.js:46:24)

       6 | 
       7 | console.error = function (message) {
    >  8 |   error.apply(console, arguments); // keep default behaviour
         |         ^
       9 |   throw (message instanceof Error ? message : new Error(message));
      10 | };
      11 | 

      at console.Object.<anonymous>.console.error (tests/jest.overrides.js:8:9)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (node_modules/react-dom/cjs/react-dom.development.js:23914:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21840:5)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12467:5)
      at SetupTab.Object.<anonymous>.Component.setState (node_modules/react/cjs/react.development.js:365:16)

/Users/runner/work/invest-workbench/invest-workbench/tests/jest.overrides.js:25
  throw message instanceof Error ? message : new Error(message);
  ^

Error: Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 
    at console.Object.<anonymous>.console.error (/Users/runner/work/invest-workbench/invest-workbench/tests/jest.overrides.js:9:47)
    at printWarning (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-dom/cjs/react-dom-test-utils.development.js:67:30)
    at error (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-dom/cjs/react-dom-test-utils.development.js:43:5)
    at onDone (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1034:9)
    at /Users/runner/work/invest-workbench/invest-workbench/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1081:13
    at Immediate.<anonymous> (/Users/runner/work/invest-workbench/invest-workbench/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1006:9)
    at processImmediate (internal/timers.js:464:21)
```

https://github.com/natcap/invest-workbench/pull/154/checks?check_run_id=3001910418

**Comment by davemfish** [comment]
My best guess is that this is happening because we have `setState` called from some async functions in the `SetupTab` component, namely within `investValidate` and `callUISpecFunctions`.

When a test completes, `SetupTab` is unmounted. But tests might complete when simple assertions pass that don't depend on these async tasks. So the async tasks were started, but the component unmounted before they finished, hence the "can't perform state update on an unmounted component."

React warns against solving this with a simple conditional to check if the component is still mounted before calling the `setState`. https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

The suggestion then is to wrap async tasks like this in a new Promise that has a "cancel" method so it can be canceled explicitly during `componentWillUnmount`. It's kind of ugly, but I guess it's the right thing to do? See example from the above link.
