### ISSUE TITLE
Habitat Quality prop warnings

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest-workbench#172]
When I was testing the Workbench for PR #171 I decided to use the Habitat Quality model. While running I noticed these prop warnings under the inspect panel. I had entered 0.99 for half saturation.

>Warning: Failed prop type: Invalid prop `argsValues.half_saturation_constant.value` supplied to `ArgsForm`.
    at ArgsForm (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\SetupTab\ArgsForm\index.js:61:34)
    at SetupTab (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\SetupTab\index.js:124:34)
    at div
    at Transition (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-transition-group\cjs\Transition.js:133:30)
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Fade.js:40:24
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabPane.js:51:24
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContent.js:21:23
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Col.js:23:23
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Row.js:25:23
    at TabContainer (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContainer.js:21:62)
    at InvestTab (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\InvestTab\index.js:156:34)
    at div
    at Transition (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-transition-group\cjs\Transition.js:133:30)
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Fade.js:40:24
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabPane.js:51:24
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContent.js:21:23
    at TabContainer (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContainer.js:21:62)
    at App (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\app.js:91:34)

>react_devtools_backend.js:2273 Warning: Failed prop type: Invalid prop `value` supplied to `ArgInput`.
    at ArgInput (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\SetupTab\ArgInput\index.js:139:34)
    at ArgsForm (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\SetupTab\ArgsForm\index.js:61:34)
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Row.js:25:23
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Container.js:24:23
    at SetupTab (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\SetupTab\index.js:124:34)
    at div
    at Transition (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-transition-group\cjs\Transition.js:133:30)
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Fade.js:40:24
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabPane.js:51:24
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContent.js:21:23
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Col.js:23:23
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Row.js:25:23
    at TabContainer (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContainer.js:21:62)
    at InvestTab (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\components\InvestTab\index.js:156:34)
    at div
    at Transition (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-transition-group\cjs\Transition.js:133:30)
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\Fade.js:40:24
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabPane.js:51:24
    at div
    at C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContent.js:21:23
    at TabContainer (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\node_modules\react-bootstrap\cjs\TabContainer.js:21:62)
    at App (C:\Users\ddenu\Workspace\NatCap\Repositories\temp-repos\dave-invest-workbench\build\renderer\app.js:91:34)

**Comment by dcdenu4** [comment]
Hmmm, I'm not able to reproduce it. 🤷‍♂️ . I'll go ahead and mark it closed, we can reopen it again if it pops up.
