### ISSUE TITLE
Various issues with rendering invest logs

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#34]
The LogTab component seems to reach some unexpected states leading to these errors:

`TypeError: Cannot read property 'unwatch' of null
    at LogTab.componentDidUpdate (/home/dmf/projects/invest-gui/src/components/LogTab/index.jsx:84:19)`

and intermittently:
```
ENOSPC: System limit for number of file watchers reached, watch '/home/dmf/projects/invest-gui/runs/carbon/InVEST-natcap.invest.carbon-log-2020-07-13--08_41_02.txt'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Proxy.watch (fs.js:1329:11)
    at Tail.watch (/home/dmf/projects/invest-gui/node_modules/tail/lib/tail.js:147:32)
    at new Tail (/home/dmf/projects/invest-gui/node_modules/tail/lib/tail.js:87:10)
    at LogTab.componentDidUpdate (/home/dmf/projects/invest-gui/src/components/LogTab/index.jsx:61:21)
```

Kind of tricky to reproduce, but trying to load a recent session that no longer exists on disk might be part of the problem.

**Comment by davemfish** [comment]
closing this after the refactor in #44
